version: "2"

services:
  p-next-metron:
    image: p-next-metron:latest
    build:
      context: .
      dockerfile: ./dockerfiles/app.docker
    container_name: "p-next-metron"
    env_file: .env.production
    ports:
      - "3000:3000"
